export const tags = {
  User: "User",
  Customer: "Customer",
  BookPurchase: "BookPurchase",
  Purchase: "Purchase",
  Sales: "Sales",
  PurchaseRetrun: "PurchaseRetrun",
  BookSale: "BookSale",
  Book: "Book",
  EmpBookAssign: "EmpBookAssign",
  Payment: "Payment",
  Category: "Category",
  Brand: "Brand",
  Product: "Product",
  Unit: "Unit",
  BaseUnit: "BaseUnit",
  Warehouse: "Warehouse",
} as const;
