export const divisionOptions = [
  { value: "dhaka", label: "Dhaka" },
  { value: "chattogram", label: "Chattogram" },
  { value: "rajshahi", label: "Rajshahi" },
  { value: "khulna", label: "Khulna" },
  { value: "sylhet", label: "Sylhet" },
  { value: "barishal", label: "Barishal" },
  { value: "rangpur", label: "Rangpur" },
  { value: "mymensingh", label: "Mymensingh" },
];
export const districtOpsions = (division: string) => {
  const districts = [
    { value: "dhaka", label: "Dhaka", division: "dhaka" },
    { value: "faridpur", label: "Faridpur", division: "dhaka" },
    { value: "gazipur", label: "Gazipur", division: "dhaka" },
    { value: "gopalganj", label: "Gopalganj", division: "dhaka" },
    { value: "kishoreganj", label: "Kishoreganj", division: "dhaka" },
    { value: "madaripur", label: "Madaripur", division: "dhaka" },
    { value: "manikganj", label: "Manikganj", division: "dhaka" },
    { value: "munshiganj", label: "Munshiganj", division: "dhaka" },
    { value: "narayanganj", label: "Narayanganj", division: "dhaka" },
    { value: "narsingdi", label: "Narsingdi", division: "dhaka" },
    { value: "rajbari", label: "Rajbari", division: "dhaka" },
    { value: "shariatpur", label: "Shariatpur", division: "dhaka" },
    { value: "tangail", label: "Tangail", division: "dhaka" },
    { value: "chattogram", label: "Chattogram", division: "chattogram" },
    { value: "bandarban", label: "Bandarban", division: "chattogram" },
    { value: "brahmanbaria", label: "Brahmanbaria", division: "chattogram" },
    { value: "chandpur", label: "Chandpur", division: "chattogram" },
    { value: "coxsbazar", label: "Cox's Bazar", division: "chattogram" },
    { value: "cumilla", label: "Cumilla", division: "chattogram" },
    { value: "feni", label: "Feni", division: "chattogram" },
    { value: "khagrachari", label: "Khagrachari", division: "chattogram" },
    { value: "lakshmipur", label: "Lakshmipur", division: "chattogram" },
    { value: "noakhali", label: "Noakhali", division: "chattogram" },
    { value: "rangamati", label: "Rangamati", division: "chattogram" },
    { value: "rajshahi", label: "Rajshahi", division: "rajshahi" },
    { value: "bogura", label: "Bogura", division: "rajshahi" },
    {
      value: "chapainawabganj",
      label: "Chapainawabganj",
      division: "rajshahi",
    },
    { value: "joypurhat", label: "Joypurhat", division: "rajshahi" },
    { value: "naogaon", label: "Naogaon", division: "rajshahi" },
    { value: "natore", label: "Natore", division: "rajshahi" },
    { value: "pabna", label: "Pabna", division: "rajshahi" },
    { value: "sirajganj", label: "Sirajganj", division: "rajshahi" },
    { value: "khulna", label: "Khulna", division: "khulna" },
    { value: "bagerhat", label: "Bagerhat", division: "khulna" },
    { value: "chuadanga", label: "Chuadanga", division: "khulna" },
    { value: "jashore", label: "Jashore", division: "khulna" },
    { value: "jhenaidah", label: "Jhenaidah", division: "khulna" },
    { value: "kushtia", label: "Kushtia", division: "khulna" },
    { value: "magura", label: "Magura", division: "khulna" },
    { value: "meherpur", label: "Meherpur", division: "khulna" },
    { value: "narail", label: "Narail", division: "khulna" },
    { value: "satkhira", label: "Satkhira", division: "khulna" },
    { value: "sylhet", label: "Sylhet", division: "sylhet" },
    { value: "habiganj", label: "Habiganj", division: "sylhet" },
    { value: "moulvibazar", label: "Moulvibazar", division: "sylhet" },
    { value: "sunamganj", label: "Sunamganj", division: "sylhet" },
    { value: "barishal", label: "Barishal", division: "barishal" },
    { value: "barguna", label: "Barguna", division: "barishal" },
    { value: "bhola", label: "Bhola", division: "barishal" },
    { value: "jhalokati", label: "Jhalokati", division: "barishal" },
    { value: "patuakhali", label: "Patuakhali", division: "barishal" },
    { value: "pirojpur", label: "Pirojpur", division: "barishal" },
    { value: "rangpur", label: "Rangpur", division: "rangpur" },
    { value: "dinajpur", label: "Dinajpur", division: "rangpur" },
    { value: "gaibandha", label: "Gaibandha", division: "rangpur" },
    { value: "kurigram", label: "Kurigram", division: "rangpur" },
    { value: "lalmonirhat", label: "Lalmonirhat", division: "rangpur" },
    { value: "nilphamari", label: "Nilphamari", division: "rangpur" },
    { value: "panchagarh", label: "Panchagarh", division: "rangpur" },
    { value: "thakurgaon", label: "Thakurgaon", division: "rangpur" },
    { value: "mymensingh", label: "Mymensingh", division: "mymensingh" },
    { value: "jamalpur", label: "Jamalpur", division: "mymensingh" },
    { value: "netrokona", label: "Netrokona", division: "mymensingh" },
    { value: "sherpur", label: "Sherpur", division: "mymensingh" },
  ];
  return districts.filter((district) => district.division === division) || [];
};
